//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_340.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentData
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
        public string StuentPhone { get; set; }
        public System.DateTime StudentDOB { get; set; }
        public string StudentGender { get; set; }
        public string StudentAddress { get; set; }
        public Nullable<int> StudentCountry { get; set; }
        public Nullable<int> StudentState { get; set; }
        public Nullable<int> StudentCity { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
    }
}
