//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int studentid { get; set; }
        public string studentname { get; set; }
        public string studentemail { get; set; }
        public string studentphone { get; set; }
        public System.DateTime studentdob { get; set; }
        public string studentgender { get; set; }
        public string studentaddress { get; set; }
        public Nullable<int> studentcountry { get; set; }
        public Nullable<int> stuentstate { get; set; }
        public Nullable<int> studentcity { get; set; }
        public string studentpincode { get; set; }
    
        public virtual city city { get; set; }
        public virtual country country { get; set; }
        public virtual state state { get; set; }
    }
}
